# Form implementation generated from reading ui file 'account_creation.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fnbuno logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background: rgb(225, 225, 225)}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fname_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fname_input.setGeometry(QtCore.QRect(120, 70, 231, 20))
        self.fname_input.setObjectName("fname_input")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(120, 170, 231, 20))
        self.password_input.setObjectName("password_input")
        self.lname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.lname_label.setGeometry(QtCore.QRect(120, 100, 61, 16))
        self.lname_label.setObjectName("lname_label")
        self.lname_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lname_input.setGeometry(QtCore.QRect(120, 120, 231, 20))
        self.lname_input.setObjectName("lname_input")
        self.password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(120, 150, 61, 16))
        self.password_label.setObjectName("password_label")
        self.fname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.fname_label.setGeometry(QtCore.QRect(120, 50, 61, 16))
        self.fname_label.setObjectName("fname_label")
        self.password_confirm_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_confirm_label.setGeometry(QtCore.QRect(120, 200, 101, 16))
        self.password_confirm_label.setObjectName("password_confirm_label")
        self.password_confirm_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_confirm_input.setGeometry(QtCore.QRect(120, 220, 231, 20))
        self.password_confirm_input.setObjectName("password_confirm_input")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 250, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.welcome_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(60, 10, 361, 41))
        self.welcome_label.setObjectName("welcome_label")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(180, 270, 131, 31))
        self.error_label.setObjectName("error_label")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 300, 471, 171))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("fnbuno logo.png"))
        self.logo.setObjectName("logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome to FNBUNO. Please create an account."))
        self.lname_label.setText(_translate("MainWindow", "Last Name"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.fname_label.setText(_translate("MainWindow", "First Name"))
        self.password_confirm_label.setText(_translate("MainWindow", "Confirm Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Create my account"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to the First National Bank of the University of Nebraska at Omaha"))
        self.error_label.setText(_translate("MainWindow", "Please create an account."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
