# Form implementation generated from reading ui file 'launch_screen.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(500, 500)
        mainWindow.setMinimumSize(QtCore.QSize(500, 500))
        mainWindow.setMaximumSize(QtCore.QSize(500, 500))
        mainWindow.setBaseSize(QtCore.QSize(10, 10))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fnbuno logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("QMainWindow {background: rgb(225, 225, 225)}\n"
"")
        self.Welcome_2 = QtWidgets.QWidget(parent=mainWindow)
        self.Welcome_2.setEnabled(True)
        self.Welcome_2.setObjectName("Welcome_2")
        self.welcome_label = QtWidgets.QLabel(parent=self.Welcome_2)
        self.welcome_label.setGeometry(QtCore.QRect(60, 10, 361, 41))
        self.welcome_label.setObjectName("welcome_label")
        self.fname_label = QtWidgets.QLabel(parent=self.Welcome_2)
        self.fname_label.setGeometry(QtCore.QRect(70, 100, 61, 16))
        self.fname_label.setObjectName("fname_label")
        self.lname_label = QtWidgets.QLabel(parent=self.Welcome_2)
        self.lname_label.setGeometry(QtCore.QRect(70, 130, 61, 16))
        self.lname_label.setObjectName("lname_label")
        self.password_label = QtWidgets.QLabel(parent=self.Welcome_2)
        self.password_label.setGeometry(QtCore.QRect(70, 160, 61, 16))
        self.password_label.setObjectName("password_label")
        self.fname_input = QtWidgets.QLineEdit(parent=self.Welcome_2)
        self.fname_input.setGeometry(QtCore.QRect(150, 100, 231, 20))
        self.fname_input.setObjectName("fname_input")
        self.lname_input = QtWidgets.QLineEdit(parent=self.Welcome_2)
        self.lname_input.setGeometry(QtCore.QRect(150, 130, 231, 20))
        self.lname_input.setObjectName("lname_input")
        self.password_input = QtWidgets.QLineEdit(parent=self.Welcome_2)
        self.password_input.setGeometry(QtCore.QRect(150, 160, 231, 20))
        self.password_input.setObjectName("password_input")
        self.signin_button = QtWidgets.QPushButton(parent=self.Welcome_2)
        self.signin_button.setGeometry(QtCore.QRect(200, 200, 101, 23))
        self.signin_button.setObjectName("signin_button")
        self.createaccount_label = QtWidgets.QPushButton(parent=self.Welcome_2)
        self.createaccount_label.setGeometry(QtCore.QRect(200, 230, 101, 23))
        self.createaccount_label.setObjectName("createaccount_label")
        self.error_label = QtWidgets.QLabel(parent=self.Welcome_2)
        self.error_label.setGeometry(QtCore.QRect(170, 260, 171, 31))
        self.error_label.setObjectName("error_label")
        self.logo = QtWidgets.QLabel(parent=self.Welcome_2)
        self.logo.setGeometry(QtCore.QRect(20, 300, 471, 171))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("fnbuno logo.png"))
        self.logo.setObjectName("logo")
        mainWindow.setCentralWidget(self.Welcome_2)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Welcome to FNBUNO. Please login or create an account."))
        self.welcome_label.setText(_translate("mainWindow", "Welcome to the First National Bank of the University of Nebraska at Omaha"))
        self.fname_label.setText(_translate("mainWindow", "First Name"))
        self.lname_label.setText(_translate("mainWindow", "Last Name"))
        self.password_label.setText(_translate("mainWindow", "Password"))
        self.signin_button.setText(_translate("mainWindow", "Sign in"))
        self.createaccount_label.setText(_translate("mainWindow", "Create an account"))
        self.error_label.setText(_translate("mainWindow", "Please log in or create an account."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
